# Development Environment Values Override
# This file contains development-specific overrides for kagent chart

# ==============================================================================
# DEVELOPMENT CONFIGURATION
# ==============================================================================

# Use unique names to avoid conflicts with production kagent
nameOverride: "sre-kagent"
fullnameOverride: "sre-kagent-dev"

# Use the chart version or latest stable tag instead of non-existent dev-latest
# tag: ""  # Will default to Chart version

# Development uses OpenAI with smaller model for cost efficiency
providers:
  default: openAI
  openAI:
    provider: OpenAI
    model: "gpt-4o-mini"  # Cheaper model for dev
    apiKeySecretRef: kagent-openai-dev
    apiKeySecretKey: OPENAI_API_KEY

# ==============================================================================
# CONTROLLER CONFIGURATION - DEV
# ==============================================================================

controller:
  replicas: 1
  loglevel: "debug"  # Debug logging for development
  resources:
    requests:
      cpu: 50m      # Lower resource requests for dev
      memory: 64Mi
    limits:
      cpu: 1        # Lower limits for dev
      memory: 256Mi

# ==============================================================================
# UI CONFIGURATION - DEV
# ==============================================================================

ui:
  replicas: 1
  resources:
    requests:
      cpu: 50m      # Lower resource requests for dev
      memory: 128Mi
    limits:
      cpu: 500m     # Lower limits for dev
      memory: 512Mi

# ==============================================================================
# AGENTS - SELECTIVE ENABLEMENT FOR DEV
# ==============================================================================

# Agents temporarily disabled - missing local chart dependencies
agents:
  k8s-agent:
    enabled: false    # Missing local chart
  kgateway-agent:
    enabled: false    # Missing local chart
  istio-agent:
    enabled: false    # Missing local chart
  promql-agent:
    enabled: false    # Missing local chart
  observability-agent:
    enabled: false    # Missing local chart
  argo-rollouts-agent:
    enabled: false    # Missing local chart
  helm-agent:
    enabled: false    # Missing local chart
  cilium-policy-agent:
    enabled: false    # Missing local chart
  cilium-manager-agent:
    enabled: false    # Missing local chart
  cilium-debug-agent:
    enabled: false    # Missing local chart

# ==============================================================================
# BUILT-IN TOOLS - DEV SETTINGS
# ==============================================================================

kagent-tools:
  enabled: true
  replicaCount: 1
  tools:
    loglevel: "debug"

# ==============================================================================
# EXTERNAL MCP SERVERS - DEV
# ==============================================================================

# External MCP servers temporarily disabled - missing local charts
external-mcp:
  querydoc:
    enabled: false    # Missing local chart

# ==============================================================================
# OBSERVABILITY - DEV
# ==============================================================================

otel:
  tracing:
    enabled: true     # Enable for dev debugging
    exporter:
      otlp:
        endpoint: http://host.docker.internal:4317
        timeout: 15
        insecure: true
  logging:
    enabled: true     # Enable for dev debugging
    exporter:
      otlp:
        endpoint: http://host.docker.internal:4317
        timeout: 15
        insecure: true
