apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent.fullname" . }}-controller
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.ports.port }}
      targetPort: {{ .Values.controller.service.ports.targetPort }}
      protocol: TCP
      name: controller
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: grafana-mcp
  selector:
    {{- include "kagent.controller.selectorLabels" . | nindent 4 }}
