apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kagent.fullname" . }}-controller
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "kagent.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.controller.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kagent.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (.Values.controller.podSecurityContext | default .Values.podSecurityContext) | nindent 8 }}
      serviceAccountName: {{ include "kagent.fullname" . }}-controller
      volumes:
      - name: sqlite-volume
        emptyDir:
          sizeLimit: 500Mi
          medium: Memory
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          args:
            # Use actual valid controller arguments
            - -default-model-config-name
            - {{ include "kagent.defaultModelConfigName" . | quote }}
            - -default-model-config-namespace
            - {{ include "kagent.namespace" . | quote }}
            - -zap-log-level
            - {{ .Values.controller.loglevel }}
            - -health-probe-bind-address
            - ":8082"
            - -http-server-address
            - ":{{ .Values.controller.service.ports.targetPort }}"
            - -metrics-bind-address
            - "0"
            {{- if .Values.controller.autogen.baseUrl }}
            - -autogen-base-url
            - {{ .Values.controller.autogen.baseUrl | quote }}
            {{- end }}
            {{- if .Values.controller.autogen.wsUrl }}
            - -autogen-ws-url
            - {{ .Values.controller.autogen.wsUrl | quote }}
            {{- end }}
            {{- if and .Values.controller.leaderElection .Values.controller.leaderElection.enabled }}
            - -leader-elect
            {{- end }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.registry | default .Values.registry  }}/{{ .Values.controller.image.repository }}:{{ coalesce .Values.tag .Values.controller.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy | default .Values.imagePullPolicy }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          env:
            - name: KAGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.controller.loglevel | quote }}
            - name: OTEL_TRACING_ENABLED
              value: {{ .Values.otel.tracing.enabled | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.tracing.exporter.otlp.endpoint | quote }}
            - name: OTEL_TRACING_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.tracing.exporter.otlp.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
              value: {{ .Values.otel.tracing.exporter.otlp.timeout | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
              value: {{ .Values.otel.tracing.exporter.otlp.insecure | quote }}
            - name: OTEL_LOGGING_ENABLED
              value: {{ .Values.otel.logging.enabled | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
              value: {{ .Values.otel.logging.exporter.otlp.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_TIMEOUT
              value: {{ .Values.otel.logging.exporter.otlp.timeout | quote }}
            - name: OTEL_EXPORTER_OTLP_LOGS_INSECURE
              value: {{ .Values.otel.logging.exporter.otlp.insecure | quote }}
            {{- with .Values.controller.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.service.ports.targetPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 1
            initialDelaySeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 30
          volumeMounts:
            - name: sqlite-volume
              mountPath: /sqlite-volume
        {{- if .Values.controller.autogen.enabled }}
        # AutoGen sidecar container
        - name: autogen
          image: "{{ .Values.controller.autogen.image.registry | default .Values.registry }}/{{ .Values.controller.autogen.image.repository }}:{{ .Values.controller.autogen.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.controller.autogen.image.pullPolicy | default .Values.imagePullPolicy }}
          resources:
            {{- toYaml (.Values.controller.autogen.resources | default .Values.controller.resources) | nindent 12 }}
          ports:
            - name: autogen-api
              containerPort: 8081
              protocol: TCP
          env:
            {{- with .Values.controller.autogen.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
