apiVersion: v2
name: sre-kagent-base
description: SRE Kagent Base Chart - foundational kagent deployment
type: application
version: 0.2.0
dependencies:
  - name: kagent-tools
    version: 0.0.11
    repository: oci://ghcr.io/kagent-dev/tools/helm
    condition: kagent-tools.enabled

